version: '3.9'

services:
  v2raya:
    image: mzz2017/v2raya
    container_name: 'v2raya'
    restart: always
    privileged: true
    networks:
      - host
    volumes:
      - '/etc/resolv.conf:/etc/resolv.conf'
      - '/etc/v2raya:/etc/v2raya'
